.docker:
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_HOST: docker:2375
  script:
    - export REPO=$(echo $CI_JOB_NAME | sed 's/:.*/\1/')
    - docker build -t $CI_JOB_NAME .
    - docker login -u $CI_DOCKER_GITLAB_USER -p $CI_DOCKER_GITLAB_PASSWORD $CI_REGISTRY
    - docker tag $CI_JOB_NAME registry.gitlab.com/mvochoa-docker/$CI_JOB_NAME
    - docker push registry.gitlab.com/mvochoa-docker/$CI_JOB_NAME
    - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD
    - docker tag $CI_JOB_NAME mvochoa/$CI_JOB_NAME
    - docker push mvochoa/$CI_JOB_NAME
    - while [ $# -gt 0 ]; do docker tag $CI_JOB_NAME mvochoa/$REPO:$1; docker push mvochoa/$REPO:$1; shift; done;
  after_script:
    - apk add --update curl jq bash
    - ./description.sh mvochoa/$(echo $CI_JOB_NAME | sed 's/:.*/\1/')
  tags:
    - docker

graphqldoc:latest:
  extends: .docker
  before_script:
    - cd 2.1.0-alpine3.12/
  only:
    refs:
      - master
    changes:
      - 2.1.0-alpine3.12/*
      - 2.1.0-alpine3.12/**/*

graphqldoc:2.1.0-alpine3.12:
  extends: .docker
  before_script:
    - cd 2.1.0-alpine3.12/
    - set -- 2 2-alpine
  only:
    refs:
      - master
    changes:
      - 2.1.0-alpine3.12/*
      - 2.1.0-alpine3.12/**/*

graphqldoc:1.0.0-alpine3.8:
  extends: .docker
  before_script:
    - cd 1.0.0-alpine3.8/
    - set -- 1.0.0 1.0.0-alpine
  only:
    refs:
      - master
    changes:
      - 1.0.0-alpine3.8/*
      - 1.0.0-alpine3.8/**/*
